# Generated by Django 6.0.7 on 2026-09-22 21:10

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_available_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='books/', verbose_name='Фото'),
        ),
    ]
